# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 440, 381, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.addrLn = QtWidgets.QLineEdit(self.centralwidget)
        self.addrLn.setGeometry(QtCore.QRect(90, 30, 131, 21))
        self.addrLn.setObjectName("addrLn")
        self.addrLb = QtWidgets.QLabel(self.centralwidget)
        self.addrLb.setGeometry(QtCore.QRect(90, 10, 81, 16))
        self.addrLb.setStyleSheet("QWidget#centralwidget {\n"
"    background: QColor(176, 224, 230)\n"
"}")
        self.addrLb.setObjectName("addrLb")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(480, 430, 131, 41))
        self.sendButton.setObjectName("sendButton")
        self.chat = QtWidgets.QTextEdit(self.centralwidget)
        self.chat.setGeometry(QtCore.QRect(90, 70, 381, 361))
        self.chat.setObjectName("chat")
        self.logLabel = QtWidgets.QLabel(self.centralwidget)
        self.logLabel.setGeometry(QtCore.QRect(377, 30, 81, 20))
        font = QtGui.QFont()
        font.setFamily(".SF NS Mono")
        font.setItalic(True)
        self.logLabel.setFont(font)
        self.logLabel.setText("")
        self.logLabel.setObjectName("logLabel")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(480, 21, 112, 41))
        self.connectButton.setObjectName("connectButton")
        self.portLn = QtWidgets.QLineEdit(self.centralwidget)
        self.portLn.setGeometry(QtCore.QRect(230, 30, 131, 21))
        self.portLn.setObjectName("portLn")
        self.portLb = QtWidgets.QLabel(self.centralwidget)
        self.portLb.setGeometry(QtCore.QRect(230, 10, 81, 16))
        self.portLb.setStyleSheet("QWidget#centralwidget {\n"
"    background: QColor(176, 224, 230)\n"
"}")
        self.portLb.setObjectName("portLb")
        self.currentAddr = QtWidgets.QLabel(self.centralwidget)
        self.currentAddr.setGeometry(QtCore.QRect(500, 140, 211, 16))
        font = QtGui.QFont()
        font.setFamily(".SF NS Mono")
        font.setItalic(True)
        self.currentAddr.setFont(font)
        self.currentAddr.setText("")
        self.currentAddr.setObjectName("currentAddr")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 100, 101, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addrLn.setText(_translate("MainWindow", "127.0.0.1"))
        self.addrLb.setText(_translate("MainWindow", "address"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.portLn.setText(_translate("MainWindow", "9000"))
        self.portLb.setText(_translate("MainWindow", "port"))
        self.label.setText(_translate("MainWindow", "Current addr"))
